# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Weather App' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Firebase'
  pod 'FirebaseCore'
  pod 'FirebaseMessaging'
  pod 'FirebaseCrashlytics'
  pod 'Alamofire'
  pod 'RealmSwift'
  pod 'RxSwift'
  pod 'RxCocoa'

  # Pods for Weather App

end
